Fixed logger pthread problem

diff --git a/trunk/devel/lqftp/configure b/trunk/devel/lqftp/configure
--- a/trunk/devel/lqftp/configure
+++ b/trunk/devel/lqftp/configure
@@ -4025,6 +4025,113 @@ _ACEOF
 fi
 
 
+
+havepthread=no
+echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
+if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_create ();
+int
+main ()
+{
+pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pthread_pthread_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pthread_pthread_create=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
+if test $ac_cv_lib_pthread_pthread_create = yes; then
+  havepthread=yes
+fi
+
+if test "$havepthread" = "yes" ; then
+    CPPFLAGS="${CPPFLAGS} -DHAVE_PTHREAD"
+    LDFLAGS="${LDFLAGS} -lpthread"
+fi
+
+        echo "$as_me:$LINENO: checking for debugging" >&5
+echo $ECHO_N "checking for debugging... $ECHO_C" >&6
+        # Check whether --enable-debug or --disable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval="$enable_debug"
+
+fi;
+        if test -z "$enable_debug" ; then
+                enable_debug="no"
+        elif test "$enable_debug" = "yes" ; then
+                CPPFLAGS="${CPPFLAGS} -g -D_DEBUG"
+        fi
+        echo "$as_me:$LINENO: result: $enable_debug" >&5
+echo "${ECHO_T}$enable_debug" >&6
+	echo "$as_me:$LINENO: checking for linking static library " >&5
+echo $ECHO_N "checking for linking static library ... $ECHO_C" >&6
+        # Check whether --enable-link_static or --disable-link_static was given.
+if test "${enable_link_static+set}" = set; then
+  enableval="$enable_link_static"
+
+fi;
+        if test -z "$enable_link_static" ; then
+                enable_link_static="no"
+        elif test $enable_link_static = "yes" ; then
+                CPPFLAGS="${CPPFLAGS} -static"
+                LDFLAGS="${LDFLAGS} -static"
+        fi
+        echo "$as_me:$LINENO: result: $enable_link_static" >&5
+echo "${ECHO_T}$enable_link_static" >&6
+
+
+
         echo "$as_me:$LINENO: checking for debugging" >&5
 echo $ECHO_N "checking for debugging... $ECHO_C" >&6
         # Check whether --enable-debug or --disable-debug was given.
